musician_instrument(ringo, drums).
musician_instrument(john, guitar).
musician_instrument(paul, bass).
musician_instrument(george, guitar).
musician_instrument(bowie, saxophone).
musician_instrument(bowie, guitar).
musician_instrument(bowie, piano).
musician_instrument(bowie, keyboards).
musician_instrument(bowie, harmonica).
musician_instrument(bowie, mouth_harp).
musician_instrument(bowie, koto).
musician_instrument(bowie, mandolin).
musician_instrument(bowie, recorder).
musician_instrument(bowie, viola).
musician_instrument(bowie, violin).
musician_instrument(bowie, cello).
musician_instrument(bowie, stylophone).
musician_genre(ringo, rock).
musician_genre(john, rock).
musician_genre(paul, rock).
musician_genre(george, rock).
musician_genre(ringo, pop).
musician_genre(john, pop).
musician_genre(paul, pop).
musician_genre(george, pop).
musician_genre(bowie, rock).
musician_genre(bowie, glam_rock).
musician_genre(bowie, pop).
musician_genre(bowie, electronic).
musician_genre(bowie, experimental).
